CBDEMO-128

diff --git a/.cloudbees/workflows/my-automation-6.yaml b/.cloudbees/workflows/my-automation-6.yaml
--- a/.cloudbees/workflows/my-automation-6.yaml
+++ b/.cloudbees/workflows/my-automation-6.yaml
@@ -19,25 +19,30 @@ jobs:
       - name: Get Commit Info
         uses: docker://alpine/git:latest
         run: |
+          COMMIT_ID=$(git rev-parse HEAD)
+          COMMIT_MSG=$(git log -1 --pretty=%B)
 
-           COMMIT_ID=$(git rev-parse HEAD)
-           COMMIT_MSG=$(git log -1 --pretty=%B)
-
-           # Validate commit message to include JIRA issue key (format: ABC-123)
-           if [[ ! "$COMMIT_MSG" =~ ([A-Z]+-[0-9]+) ]]; then
-            echo "Error: Commit message must include a JIRA issue key (e.g., CBDEMO-131)." >&2
+          # Validate commit message to include JIRA issue key
+          if [[ ! "$COMMIT_MSG" =~ ([A-Z]+-[0-9]+) ]]; then
+            echo "Error: Commit message must include a valid JIRA issue key." >&2
             exit 1
-           fi
+          fi
 
-           # Extract JIRA issue key from commit message
-           JIRA_ISSUE_KEY="${BASH_REMATCH[1]}"
+          # Extract the JIRA issue key from the commit message
+          JIRA_ISSUE_KEY="${BASH_REMATCH[1]}"
 
-              # Save commit info for the next steps
-            echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
-            echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
+          # Save commit info for the next steps
+          echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
+          echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
+          echo "jira_issue_key=${JIRA_ISSUE_KEY}" >> $CLOUDBEES_OUTPUTS/jira_issue_key
 
-
-      
+      - name: Fetch JIRA Metrics
+        uses: docker://alpine/curl:latest
+        run: |
+          JIRA_API_URL="https://cloudbees.atlassian.net/rest/api/2/issue/${{ steps.get_commit_info.outputs.jira_issue_key }}"
+         
+          response=$(curl -s -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }} ${JIRA_API_URL})
+          echo "jira_response=${response}" >> $CLOUDBEES_OUTPUTS/jira_response
 
       - name: Build
         uses: docker://maven:3-eclipse-temurin-17
