CBDEMO-152

diff --git a/.cloudbees/workflows/my-automation-6.yaml b/.cloudbees/workflows/my-automation-6.yaml
--- a/.cloudbees/workflows/my-automation-6.yaml
+++ b/.cloudbees/workflows/my-automation-6.yaml
@@ -17,6 +17,14 @@ jobs:
       - name: Checkout Code
         uses: cloudbees-io/checkout@v1
 
+      - name: Enforce Jira Issue Key
+        uses: docker://alpine/git:latest
+        run: |
+          if ! git log -1 --pretty=%B | grep -qE 'CBDEMO-[0-9]+'; then
+            echo "Error: Commit message must include a Jira issue key (e.g., CBDEMO-152)."
+            exit 1
+          fi
+
       - name: Build with Maven
         uses: docker://maven:3-eclipse-temurin-17
         run: mvn clean install
@@ -34,18 +42,3 @@ jobs:
           sonar-exclusion: src/main/java
           cover-file-name: ./pom.xml
           language: "LANGUAGE_JAVA"
-
-      - name: Configure git user
-        uses: docker://alpine/git:latest
-        run: |
-          git config --global user.email "c_aannamalai@cloudbees.com"
-          git config --global user.name "cashokannamalai"
-
-      - name: Commit changes with JIRA key
-        id: commit_changes
-        uses: docker://alpine/git:latest
-        run: |
-          JIRA_KEY="CBDEMO-122"
-          git add .
-          git commit -m "$JIRA_KEY: Commit message describing changes"
-          git push origin main
