CBDEMO-122

diff --git a/.cloudbees/workflows/my-automation-6.yaml b/.cloudbees/workflows/my-automation-6.yaml
--- a/.cloudbees/workflows/my-automation-6.yaml
+++ b/.cloudbees/workflows/my-automation-6.yaml
@@ -7,37 +7,30 @@ on:
       - main
 jobs:
   Build:
-  
     steps:
       - name: Configure git
-        id: buildinfo12
         uses: docker://alpine/git:latest
         run: |
           git config --global --add safe.directory /cloudbees/workspace
 
       - name: Checkout
-        id: commiti
         uses: cloudbees-io/checkout@v1
-
 
       - name: Get Commit Info
         uses: docker://alpine/git:latest
-        id: commitinfo
         run: |
-         COMMIT_ID=$(git rev-parse HEAD)
-         COMMIT_MSG=$(git log -1 --pretty=%B)
-
-         
-         if [[ ! "$COMMIT_MSG" =~ CBDEMO-122 ]]; then
-          echo "Error: Commit message must include the JIRA issue key CBDEMO-122." >&2
-          exit 1
-         fi
-
-         echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
-         echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
+          COMMIT_ID=$(git rev-parse HEAD)
+          COMMIT_MSG=$(git log -1 --pretty=%B)
+          
+          if [[ ! "$COMMIT_MSG" =~ CBDEMO-122 ]]; then
+            echo "Error: Commit message must include the JIRA issue key CBDEMO-122." >&2
+            exit 1
+          fi
+          
+          echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
+          echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
 
       - name: Build
-        id: buildinfo
         uses: docker://maven:3-eclipse-temurin-17
         run: |
           mvn clean install
