test

diff --git a/.cloudbees/workflows/my-automation-6.yaml b/.cloudbees/workflows/my-automation-6.yaml
--- a/.cloudbees/workflows/my-automation-6.yaml
+++ b/.cloudbees/workflows/my-automation-6.yaml
@@ -6,8 +6,7 @@ on:
     branches:
       - main
 jobs:
-  Build:
-
+  ValidateCommits:
     steps:
       - name: Configure git
         id: info
@@ -15,21 +14,26 @@ jobs:
         run: |
           git config --global --add safe.directory /cloudbees/workspace
 
+      - name: Fetch Commit Messages
+        id: fetch-commits
+        uses: docker://alpine/git:latest
+        run: |
+          git fetch --depth=2 
+          git log --pretty=format:"%s" HEAD..HEAD~1 > commit_messages.txt
+
+      - name: Validate Jira Issue Keys
+        id: validate-jira
+        uses: docker://alpine/git:latest
+        run: |
+          grep -Eo 'CBDEMO-135' commit_messages.txt || (echo "Jira issue key missing in commit message" && exit 1)
+        
+
+  Build:
+    needs: ValidateCommits
+    steps:
       - name: Checkout
         id: Checkout
         uses: cloudbees-io/checkout@v1
-
-      - name: Validate commit message for JIRA issue key
-        id: validate-commit
-        uses: docker://alpine/git:latest
-        run: |
-          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-          if ! echo "$COMMIT_MESSAGE" | grep -E '(CBDEMO-[0-9]+)'; then
-            echo "Commit message does not contain a valid CBDEMO issue key. Aborting."
-            exit 1
-          else
-            echo "Commit message contains a valid CBDEMO issue key."
-          fi
 
       - name: Build
         id: Buildinfo
